# Generated by Django 3.0.2 on 2020-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Imagen'),
        ),
    ]
